name: CI

on:
  push:
    branches: [ main, clean-main ]
  pull_request:
    branches: [ main, clean-main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
      - name: Configure
        run: cmake -S . -B build -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - name: Build
        run: cmake --build build --config RelWithDebInfo -- -j
      - name: Run tests
        run: ctest --test-dir build -C RelWithDebInfo --output-on-failure
      - name: RT-safety grep
        run: |
          grep -nR --exclude-dir=build -E "std::mutex|std::thread|malloc\(|new |std::vector<" Source/Core Source/Synthesis || true